export const LEARN_INFINITE_LOGO = "../../../assets/logos/Logo.png";
export const CART_IMAGE = "../../../assets/icons/Image 10.png";
export const SEARCH_ICON = "../../../assets/icons/magnifying-glass-solid.svg";
export const PROFILE_ICON ="../../../assets/icons/profile.png";
export const BOOK_IMAGE ="../../../assets/images/book.png";
export const STUDY_IMAGE ="../../../assets/images/study.png";
export const STAR_IMAGE = "../../../assets/images/star.png";
export const RIGHT_ARROW_ICON = "../../../assets/icons/angle-right-solid.svg";
export const LEFT_ARROW_ICON = "../../../assets/icons/angle-left-solid.svg";
